version: '2'
services:
  db:
    image: mysql
    volumes:
      - ./var/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
  php:
    build: ./docker/php
    volumes:
      - ./src:/var/www/html/app
      - ./var/php/.composer:/root/.composer
    links:
      - db
  nginx:
    build: ./docker/nginx
    volumes_from:
      - php
    links:
      - php
    ports:
      - 8080:8080
